### ISSUE TITLE
To update title section of changlog/config.yaml

### ISSUE THREAD

**Issue by justjais** [ansible-collections/ansible.network#17]
##### SUMMARY

To update title section of changlog/config.yaml. ref: [Title](https://github.com/ansible-collections/ansible.network/blob/main/changelogs/config.yaml#L29)

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

**Comment by rohitthakur2590** [comment]
resolved by : https://github.com/ansible-collections/ansible.network/pull/14
