### ISSUE TITLE
README update prior to resource manager

### ISSUE THREAD

**Issue by cidrblock** [ansible-collections/ansible.network#18]
Update README and repo description to better clarify the ansible.network collection is primarily a meta collection, but the inclusion of very generic multi-platform content maybe be considered under some circumstances.  Plugins should be located in  different, dependent collections.  Content inclusion will be at the discretion of the collection maintainers with ongoing operational
 overhead and supportability both considered.

**Comment by trishnaguha** [comment]
@rohitthakur2590 Can we close this issue?
