### ISSUE TITLE
Be sure the collection is tested against 2.11 and contains sanity/ignore-2.12.txt if applicable

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/ansible.network#2]
##### SUMMARY
https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100

If irrelevant, feel free to close the issue

**Comment by trishnaguha** [comment]
@rohitthakur2590 Could you please look into this issue? Shall we close it as we already test it with 2.11?

**Comment by Andersson007** [comment]
@rohitthakur2590 is the issue still relevant? If not, feel free to close.
