### ISSUE TITLE
Paramiko issues with 2.10.1 and 2.10.3 and cisco.ios collection with network_cli

### ISSUE THREAD

**Issue by IPvSean** [ansible-collections/ansible.network#30]
##### SUMMARY
I would open the issue on the cisco.ios collection but I am thinking this will end up a documentation bug as we make the leap to libssh....

Basically we are now hitting a paramiko security issue
<img width="925" alt="image" src="https://user-images.githubusercontent.com/6537680/161342589-630d2df7-87fa-4f26-9f0a-8e856b46a2dd.png">
 The issue is here: https://github.com/ansible/workshops/pull/1604

I have tested with paramiko 2.10.1 and 2.10.3

```
➜  ~ pip3 show paramiko
Name: paramiko
Version: 2.10.3
Summary: SSH2 protocol library
Home-page: https://paramiko.org
Author: Jeff Forcier
Author-email: jeff@bitprophet.org
License: LGPL
Location: /usr/local/lib/python3.9/site-packages
Requires: bcrypt, cryptography, pynacl, six
Required-by:
➜  ~ ansible --version
ansible [core 2.11.2]
  config file = /Users/sean/.ansible.cfg
  configured module search path = ['/Users/sean/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/sean/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.9 (main, Nov 21 2021, 03:23:42) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.1
  libyaml = True
```

I am getting connection problems with Cisco IOS only... whereas paramiko 2.8.1 works fine.  Arista EOS works on 2.8.1, 2.10.1 and 2.10.3

We either need to 
A) figure out a workaround and a non-security bugged paramiko version that we can tell customers
or
B) move customers to libssh....

I think in either case... this is probably more documentation than bug?  I am not sure... I did notice the network_ee is also pegged at 2.8.1 before I opened this issue...

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
connection: network_cli
with 
ansible_network_os. cisco.ios.ios

##### ANSIBLE VERSION

```paste below
2.11.2
```

##### COLLECTION VERSION

```paste below
# /Users/sean/.ansible/collections/ansible_collections
Collection                          Version
----------------------------------- -------
amazon.aws                          3.1.1
ansible.netcommon                   2.0.2
ansible.network                     1.2.0
ansible.posix                       1.3.0
ansible.product_demos               1.2.13
ansible.utils                       2.5.2
ansible.windows                     1.9.0
ansible.workshops                   1.0.11
arista.eos                          2.1.2
awx.awx                             19.4.0
azure.azcollection                  1.12.0
chocolatey.chocolatey               1.2.0
cisco.ios                           2.0.1
cisco.iosxr                         2.8.1
cisco.nxos                          2.9.0
community.aws                       3.1.0
community.crypto                    2.2.3
community.general                   4.5.0
community.mysql                     3.1.1
community.windows                   1.9.0
containers.podman                   1.9.1
f5networks.f5_modules               1.15.0
frr.frr                             1.0.3
junipernetworks.junos               2.1.0
openvswitch.openvswitch             2.1.0
redhat_cop.controller_configuration 2.1.1
redhat_cop.tower_utilities          2.0.1
vyos.vyos                           2.8.0
```

##### CONFIGURATION

```paste below
DEFAULT_STDOUT_CALLBACK(/Users/sean/.ansible.cfg) = yaml
GALAXY_SERVER_LIST(/Users/sean/.ansible.cfg) = ['release_galaxy']
HOST_KEY_CHECKING(/Users/sean/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
Mac OS

##### STEPS TO REPRODUCE
just try to connect to a Cisco IOS box, the one I have is Cisco IOS Software [Fuji], Virtual XE Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 16.9.2, RELEASE SOFTWARE (fc4)

##### EXPECTED RESULTS
connection occurs...

##### ACTUAL RESULTS
no connection

**Comment by NilashishC** [comment]
@IPvSean Are you still facing this issue? If so, could you please re-open this ticket in the cisco.ios collection? Thank you!

cc @KB-perByte

**Comment by ashwini-mhatre** [comment]
@KB-perByte @IPvSean should i moved this ticket to cisco.ios collection?

**Comment by KB-perByte** [comment]
@ashwini-mhatre this should be resolved, we can chek it once and close it of.

**Comment by NilashishC** [comment]
@IPvSean closing this ticket since it's stale for a while now. if this continues to be an issue with latest netcommon/paramiko/libssh and cisco.ios, please open a ticket in the cisco.ios repo. Thanks!
